/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_project_cs4421_project_cpuInfo */

#ifndef _Included_com_project_cs4421_project_cpuInfo
#define _Included_com_project_cs4421_project_cpuInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_project_cs4421_project_cpuInfo
 * Method:    read
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_project_cs4421_project_cpuInfo_read
  (JNIEnv *, jobject);

/*
 * Class:     com_project_cs4421_project_cpuInfo
 * Method:    coresPerSocket
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_project_cs4421_project_cpuInfo_coresPerSocket
  (JNIEnv *, jobject);

/*
 * Class:     com_project_cs4421_project_cpuInfo
 * Method:    socketCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_project_cs4421_project_cpuInfo_socketCount
  (JNIEnv *, jobject);

/*
 * Class:     com_project_cs4421_project_cpuInfo
 * Method:    getModel
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_project_cs4421_project_cpuInfo_getModel
  (JNIEnv *, jobject);

/*
 * Class:     com_project_cs4421_project_cpuInfo
 * Method:    l1dCacheSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_project_cs4421_project_cpuInfo_l1dCacheSize
  (JNIEnv *, jobject);

/*
 * Class:     com_project_cs4421_project_cpuInfo
 * Method:    l1iCacheSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_project_cs4421_project_cpuInfo_l1iCacheSize
  (JNIEnv *, jobject);

/*
 * Class:     com_project_cs4421_project_cpuInfo
 * Method:    l2CacheSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_project_cs4421_project_cpuInfo_l2CacheSize
  (JNIEnv *, jobject);

/*
 * Class:     com_project_cs4421_project_cpuInfo
 * Method:    l3CacheSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_project_cs4421_project_cpuInfo_l3CacheSize
  (JNIEnv *, jobject);

/*
 * Class:     com_project_cs4421_project_cpuInfo
 * Method:    getUserTime
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_project_cs4421_project_cpuInfo_getUserTime
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_project_cs4421_project_cpuInfo
 * Method:    getIdleTime
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_project_cs4421_project_cpuInfo_getIdleTime
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_project_cs4421_project_cpuInfo
 * Method:    getSystemTime
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_project_cs4421_project_cpuInfo_getSystemTime
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
