/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_project_cs4421_project_sysInfo */

#ifndef _Included_com_project_cs4421_project_sysInfo
#define _Included_com_project_cs4421_project_sysInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_project_cs4421_project_sysInfo
 * Method:    intExample
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_project_cs4421_project_sysInfo_intExample
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_project_cs4421_project_sysInfo
 * Method:    stringExample
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_project_cs4421_project_sysInfo_stringExample
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
