/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_project_cs4421_project_usbInfo */

#ifndef _Included_com_project_cs4421_project_usbInfo
#define _Included_com_project_cs4421_project_usbInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_project_cs4421_project_usbInfo
 * Method:    read
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_project_cs4421_project_usbInfo_read
  (JNIEnv *, jobject);

/*
 * Class:     com_project_cs4421_project_usbInfo
 * Method:    busCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_project_cs4421_project_usbInfo_busCount
  (JNIEnv *, jobject);

/*
 * Class:     com_project_cs4421_project_usbInfo
 * Method:    deviceCount
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_project_cs4421_project_usbInfo_deviceCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_project_cs4421_project_usbInfo
 * Method:    vendorID
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_project_cs4421_project_usbInfo_vendorID
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_project_cs4421_project_usbInfo
 * Method:    productID
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_project_cs4421_project_usbInfo_productID
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
